#
development:
  adapter: postgresql
  encoding: unicode
  database: blogramacao_development
  pool: 5
  username: locoworks
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blogramacao_test
  pool: 5
  username: locoworks
  password:
